export const ADD_CONDITION = 'ADD_CONDITION';
export const REMOVE_CONDITION = 'REMOVE_CONDITION';
export const UPDATE_EXPRESSION = 'UPDATE_EXPRESSION';
export const ADD_BODY_KEYWORD = 'ADD_BODY_KEYWORD';
export const ADD_CONDITION_KEYWORD = 'ADD_CONDITION_KEYWORD';
export const UPDATE_BODY = 'UPDATE_BODY';
